### PR TITLE
Adding yearbook

### PR DESCRIPTION
**Pull request by crazy4pi314**
addresses #5

### CODE REVIEW

**Comment by ltalirz** [comment]
This is great.

Instead of a sample format, I would suggest we add one section from the presenter team (we need to come up with a team name :-D), and add 3 little things here that we want to share but won't have the time to get to during the tutorial

**Comment by ltalirz** [comment]
E.g. from my side

- [Indent rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow): use colors to visualize indentation levels. Suggestion from [Bas Nijholt from our team](https://www.nijho.lt/post/vscode-extensions-and-shortcuts/)

**Comment by ltalirz** [comment]
Wow, is there a bug with Github discussion polls?

When I click "Edit" on my comment above, I see this:

image

**Comment by ltalirz** [comment]
team name: Heisensofties?

**Comment by crazy4pi314** [comment]
Updated, ready for review I think!

**Review by ltalirz — APPROVED** [review]

**Pull request merged**
